name: cypress
on: [push]
jobs:
    cypress:
        name: Cypress
        runs-on: ubuntu-16.04
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cypress run
              uses: cypress-io/github-action@v2
              env:
                NODE_ENV: development
              with:
                  start: node scripts/frontend/dev-server
                  wait-on: 'http://localhost:3030'
                  wait-on-timeout: 180
                  quiet: true
                  browser: chrome
									spec: |
										cypress/integration/e2e/consent.*.js
										cypress/integration/e2e/discussion.*.js
										cypress/integration/e2e/sign-in-gate.*.js
										cypress/integration/e2e/signedin.*.js
