name: Run Lighthouse CI
on: [push]
jobs:
    lhci:
        name: Lighthouse
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1
            - name: Use Node.js 14.15
              uses: actions/setup-node@v1
              with:
                  node-version: 14.15
            - run: make build
            - name: Install and run Lighthouse CI
              env:
                  LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
              run: |
                  npm install -g puppeteer-core@2.1.0 @lhci/cli@0.4.x
                  lhci autorun
