name: Lighthouse
on:
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron: '0 10,15 * * *'
jobs:
    lighthouse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run Lighthouse on urls and validate with budgets.json
              uses: treosh/lighthouse-ci-action@v2
              with:
                  urls: |
                        https://www.theguardian.com/uk-news/2020/feb/18/britain-to-evacuate-citizens-from-coronavirus-hit-cruise-ship-diamond-princess?dcr
                        https://www.theguardian.com/sport/blog/2020/feb/18/anya-shrubsole-world-twenty20-t20-england-cricket-the-spin?dcr
                        https://www.theguardian.com/lifeandstyle/2020/feb/18/i-laugh-maniacally-when-i-orgasm-and-my-boyfriend-can-no-longer-reach-climax?dcr
                  budgetPath: './budgets.json'
