name: Lighthouse
on: push
jobs:
    lighthouse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run Lighthouse on urls and validate with budgets.json
              uses: treosh/lighthouse-ci-action@v2
              with:
                  urls: 'https://www.theguardian.com/uk-news/2020/feb/18/britain-to-evacuate-citizens-from-coronavirus-hit-cruise-ship-diamond-princess?dcr'
                  budgetPath: './budgets.json'
